name: Query-NCAA

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Run the PowerShell Script
        shell: pwsh
        run: ./GetData.ps1
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: Commit Change
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'ChrisKibble@users.noreply.github.com'
          git commit -am "Automated Update of Data"
          git push
